/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Def = 4;
  /** RegularExpression Id. */
  int In = 5;
  /** RegularExpression Id. */
  int End = 6;
  /** RegularExpression Id. */
  int EXIT = 7;
  /** RegularExpression Id. */
  int NEW = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int PRINTLN = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int DEREF = 17;
  /** RegularExpression Id. */
  int Id = 18;
  /** RegularExpression Id. */
  int Num = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int TIMES = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int LPAR = 27;
  /** RegularExpression Id. */
  int RPAR = 28;
  /** RegularExpression Id. */
  int EL = 29;
  /** RegularExpression Id. */
  int EQ = 30;
  /** RegularExpression Id. */
  int EQUALS = 31;
  /** RegularExpression Id. */
  int ASSIGN = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int LEQ = 34;
  /** RegularExpression Id. */
  int BEQ = 35;
  /** RegularExpression Id. */
  int LT = 36;
  /** RegularExpression Id. */
  int BT = 37;
  /** RegularExpression Id. */
  int COLON = 38;
  /** RegularExpression Id. */
  int FINAL = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"def\"",
    "\"in\"",
    "\"end\"",
    "<EXIT>",
    "\"new\"",
    "\"if\"",
    "\"else\"",
    "\"then\"",
    "\"while\"",
    "\"do\"",
    "\"print\"",
    "\"println\"",
    "<BOOL>",
    "\"!\"",
    "<Id>",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"||\"",
    "\"&&\"",
    "\"~\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"=\"",
    "\"==\"",
    "\":=\"",
    "\";\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\";;\"",
  };

}
